import Foundation

enum FlashcardTranslator {
    static func suggestedBack(
        for front: String,
        fullMessageContent: String,
        existingTranslation: String
    ) -> String {
        let trimmedFront = front.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedFull = fullMessageContent.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedTranslation = existingTranslation.trimmingCharacters(in: .whitespacesAndNewlines)

        guard !trimmedTranslation.isEmpty, trimmedFront == trimmedFull else {
            return ""
        }
        return trimmedTranslation
    }

    static func suggestedPhonics(for text: String) -> String? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.isChinese(), let pinyin = trimmed.toPinyin() else { return nil }
        return pinyin
    }

    /// Pinyin for display: uses stored phonics when provided, otherwise auto-generates for Chinese text.
    static func displayPhonics(for text: String, storedPhonics: String? = nil) -> String? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.isChinese() else { return nil }

        if let storedPhonics {
            let trimmedStored = storedPhonics.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmedStored.isEmpty {
                return trimmedStored
            }
        }
        return suggestedPhonics(for: text)
    }

    /// Returns pinyin phonics for storage, or an empty string when the front has no Chinese.
    static func autoFillPhonics(for front: String) -> String {
        suggestedPhonics(for: front) ?? ""
    }

    /// True when phonics are empty or still match the auto-generated pinyin for `front`.
    static func phonicsMatchAutoGenerated(_ phonics: String, for front: String) -> Bool {
        let trimmedPhonics = phonics.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedPhonics.isEmpty else { return true }
        guard let autoPhonics = suggestedPhonics(for: front) else { return false }
        return trimmedPhonics == autoPhonics
    }

    static func translationConfiguration(for text: String) -> (source: String, target: String)? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        if trimmed.isChinese() {
            return ("zh-Hans", "en")
        }
        if trimmed.detectedLanguage() == "en" || !trimmed.containsChineseCharacters {
            return ("en", "zh-Hans")
        }
        return nil
    }
}