import Foundation
import SwiftUI
import Combine
import FSRS

struct FlashcardDraft: Equatable {
    var front: String
    var back: String
    var phonics: String
    /// Tracks the last auto-filled pinyin so manual phonics edits are not overwritten.
    var autoGeneratedPhonics: String?
    var sourceMessageId: String?
    var sourceConversationId: String?
}

enum AppSection: String, CaseIterable, Identifiable {
    case conversations
    case flashcards

    var id: String { rawValue }
}

/// Where practice-pack generation draws its vocabulary seeds from.
enum PracticeSeedSource: Equatable {
    /// Current FSRS-due vocabulary (deck catch-up path).
    case dueVocab
    /// Vocabulary graded in the most recent study session.
    case lastStudySession
    /// Explicit user multi-select on the Vocabulary tab.
    case selectedVocab(ids: [String])

    /// Stable label for logs / analytics (no associated-value noise).
    var analyticsName: String {
        switch self {
        case .dueVocab: return "dueVocab"
        case .lastStudySession: return "lastStudySession"
        case .selectedVocab: return "selectedVocab"
        }
    }
}

/// One graded card from a study session (used for weak-first practice seeding).
struct StudySessionGradedEntry: Equatable, Codable {
    let id: String
    /// `Rating.rawValue` from FSRS (`again=1`, `hard=2`, `good=3`, `easy=4`).
    let gradeRawValue: Int

    init(id: String, grade: Rating) {
        self.id = id
        self.gradeRawValue = grade.rawValue
    }

    var rating: Rating? {
        Rating(rawValue: gradeRawValue)
    }

    /// Again / Hard — prefer these when capping seeds for practice.
    var isWeak: Bool {
        switch rating {
        case .again, .hard: return true
        default: return false
        }
    }
}

/// Record of cards graded during a study session (for post-study practice).
/// Persisted briefly in UserDefaults so practice survives app relaunch.
struct StudySessionSnapshot: Equatable, Codable {
    let kind: FlashcardKind
    var gradedEntries: [StudySessionGradedEntry]
    var completedAt: Date

    var gradedCardIds: [String] {
        gradedEntries.map(\.id)
    }

    var weakGradeCount: Int {
        gradedEntries.filter(\.isWeak).count
    }

    init(kind: FlashcardKind, gradedEntries: [StudySessionGradedEntry] = [], completedAt: Date = Date()) {
        self.kind = kind
        self.gradedEntries = gradedEntries
        self.completedAt = completedAt
    }
}

/// UserDefaults persistence for the last study session (TTL-based).
enum StudySessionStore {
    static let defaultsKey = "flashcard.lastStudySession.v1"
    /// How long a finished study session remains available for practice after app relaunch.
    static let ttl: TimeInterval = 24 * 60 * 60

    static func save(_ snapshot: StudySessionSnapshot?) {
        let defaults = UserDefaults.standard
        guard let snapshot, !snapshot.gradedEntries.isEmpty else {
            defaults.removeObject(forKey: defaultsKey)
            return
        }
        do {
            let data = try JSONEncoder().encode(snapshot)
            defaults.set(data, forKey: defaultsKey)
        } catch {
            defaults.removeObject(forKey: defaultsKey)
        }
    }

    static func load(now: Date = Date()) -> StudySessionSnapshot? {
        let defaults = UserDefaults.standard
        guard let data = defaults.data(forKey: defaultsKey) else { return nil }
        do {
            let snapshot = try JSONDecoder().decode(StudySessionSnapshot.self, from: data)
            if now.timeIntervalSince(snapshot.completedAt) > ttl {
                defaults.removeObject(forKey: defaultsKey)
                return nil
            }
            if snapshot.gradedEntries.isEmpty {
                defaults.removeObject(forKey: defaultsKey)
                return nil
            }
            return snapshot
        } catch {
            defaults.removeObject(forKey: defaultsKey)
            return nil
        }
    }

    static func clear() {
        UserDefaults.standard.removeObject(forKey: defaultsKey)
    }
}

@MainActor
final class FlashcardViewModel: ObservableObject {
    private let dbManager = DatabaseManager()
    private let apiManager = APIManager()
    private var practiceGenerationTask: Task<Void, Never>?

    @Published var flashcards: [Flashcard] = []
    /// Primary due badge (vocabulary due). Kept for sidebar / existing call sites.
    @Published var dueCount: Int = 0
    @Published var vocabDueCount: Int = 0
    @Published var exampleDueCount: Int = 0
    /// Active library tab: Vocabulary (library) vs Examples (gym).
    @Published var selectedDeckKind: FlashcardKind = .vocab
    @Published var searchText: String = ""
    /// Multi-select mode on Vocabulary for manual practice seeds.
    @Published var isSelectingVocabForPractice = false
    /// Ordered vocab card ids chosen as practice seeds (max `PracticeGenerationConfig.maxDueSeeds`).
    @Published var selectedVocabSeedIds: [String] = []
    @Published var draft: FlashcardDraft?
    @Published var editingFlashcardId: String?
    @Published var isShowingCreateSheet = false
    @Published var isTranslatingDraft = false
    @Published var duplicateWarning = false
    @Published var saveError: String?

    @Published var isShowingReviewSession = false
    @Published var reviewQueue: [Flashcard] = []
    @Published var currentReviewIndex = 0
    @Published var isAnswerRevealed = false
    @Published var reviewComplete = false
    /// Kind of the active (or just finished) review session.
    @Published private(set) var currentReviewKind: FlashcardKind = .vocab
    /// Graded cards from the latest study session; survives dismiss for post-study practice.
    @Published private(set) var lastStudySession: StudySessionSnapshot?

    // MARK: Practice pack (ephemeral; not part of the main deck)

    @Published var practicePack: PracticePack?
    @Published var isGeneratingPractice = false
    @Published var practiceError: String?
    @Published var practiceInfoMessage: String?
    @Published var isShowingPracticePreview = false
    @Published var isShowingPracticeSession = false
    /// Set when leaving the preview sheet to open the session (avoids discard on preview dismiss).
    @Published var pendingPracticeSessionStart = false
    @Published var practiceQueue: [PracticeCard] = []
    @Published var currentPracticeIndex = 0
    @Published var isPracticeAnswerRevealed = false
    @Published var practiceComplete = false
    /// Practice cards the user wants to pin into the main deck.
    @Published var selectedPracticeCardIds: Set<String> = []
    /// Practice cards already saved this pack (for UI badges).
    @Published var savedPracticeCardIds: Set<String> = []
    /// Cards currently being regenerated one-at-a-time.
    @Published var regeneratingPracticeCardIds: Set<String> = []
    /// Simple (comprehensible) vs Natural (legacy freer prompts). Persisted in UserDefaults.
    @Published var practiceSentenceStyle: PracticeSentenceStyle {
        didSet {
            UserDefaults.standard.set(
                practiceSentenceStyle.rawValue,
                forKey: PracticeSentenceStyle.userDefaultsKey
            )
        }
    }

    /// Last LLM config used for practice generation (for regenerate from preview).
    private var lastPracticeLLMEndpoint: String?
    private var lastPracticeLLMModel: String?
    private var lastPracticeAppLanguage: AppLanguage = .en
    /// Seed source used for the current/last pack generation (for regenerate).
    private var lastPracticeSeedSource: PracticeSeedSource = .dueVocab
    private var itemRegenerationTasks: [String: Task<Void, Never>] = [:]

    var onLog: ((String) -> Void)? {
        didSet {
            apiManager.onLog = { [weak self] message in
                self?.onLog?(message)
            }
        }
    }

    var currentReviewCard: Flashcard? {
        guard currentReviewIndex < reviewQueue.count else { return nil }
        return reviewQueue[currentReviewIndex]
    }

    var currentPracticeCard: PracticeCard? {
        guard currentPracticeIndex < practiceQueue.count else { return nil }
        return practiceQueue[currentPracticeIndex]
    }

    var isEditing: Bool { editingFlashcardId != nil }

    /// True when due vocab, last study session, or a manual selection can seed practice.
    var canStartPractice: Bool {
        !isGeneratingPractice
            && (vocabDueCount > 0 || hasLastStudySessionSeeds || hasSelectedVocabSeeds)
    }

    /// Resolved vocab cards from the last study session (missing ids dropped).
    var hasLastStudySessionSeeds: Bool {
        !resolveLastStudySessionCards().isEmpty
    }

    var lastStudySessionSeedCount: Int {
        resolveLastStudySessionCards().count
    }

    var selectedVocabSeedCount: Int {
        selectedVocabSeedIds.count
    }

    var hasSelectedVocabSeeds: Bool {
        !resolveSelectedVocabCards().isEmpty
    }

    /// At the hard cap for manual practice seeds.
    var isVocabSeedSelectionAtLimit: Bool {
        selectedVocabSeedIds.count >= PracticeGenerationConfig.maxDueSeeds
    }

    /// Completion-screen CTA: vocab session with at least one graded card still in the deck.
    var canOfferPostStudyPractice: Bool {
        guard currentReviewKind == .vocab else { return false }
        return hasLastStudySessionSeeds
    }

    /// Deck button default: prefer due when available, else last study session.
    /// Manual selection uses an explicit "Practice selected" action instead.
    var preferredDeckPracticeSeedSource: PracticeSeedSource {
        vocabDueCount > 0 ? .dueVocab : .lastStudySession
    }

    /// Seed sources available from the deck Practice control (not manual multi-select).
    var availableDeckPracticeSeedSources: [PracticeSeedSource] {
        var sources: [PracticeSeedSource] = []
        if !resolvePracticeSeeds(source: .dueVocab).isEmpty {
            sources.append(.dueVocab)
        }
        if hasLastStudySessionSeeds {
            sources.append(.lastStudySession)
        }
        return sources
    }

    /// Show a seed-source menu when more than one automatic source is available.
    var showsPracticeSeedMenu: Bool {
        availableDeckPracticeSeedSources.count > 1
    }

    /// Seed source for the current manual vocabulary selection.
    var selectedVocabPracticeSeedSource: PracticeSeedSource {
        .selectedVocab(ids: selectedVocabSeedIds)
    }

    /// Count of seeds that would be used for a deck source (after resolve + cap).
    func practiceSeedCount(for source: PracticeSeedSource) -> Int {
        resolvePracticeSeeds(source: source).count
    }

    var selectedPracticeCards: [PracticeCard] {
        let source = practicePack?.cards ?? practiceQueue
        return source.filter { selectedPracticeCardIds.contains($0.id) }
    }

    var hasPracticeSelection: Bool {
        !selectedPracticeCardIds.isEmpty
    }

    var flashcardsForSelectedKind: [Flashcard] {
        flashcards.filter { $0.kind == selectedDeckKind }
    }

    var dueCountForSelectedKind: Int {
        selectedDeckKind == .vocab ? vocabDueCount : exampleDueCount
    }

    var filteredFlashcards: [Flashcard] {
        let base = flashcardsForSelectedKind
        let query = searchText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !query.isEmpty else { return base }

        return base.filter { card in
            card.front.localizedCaseInsensitiveContains(query)
                || card.back.localizedCaseInsensitiveContains(query)
                || (card.phonics?.localizedCaseInsensitiveContains(query) ?? false)
        }
    }

    /// Resolve display label for an example's parent vocab front.
    func parentFrontLabel(for card: Flashcard) -> String? {
        guard card.kind == .example, let parentId = card.parentFlashcardId else { return nil }
        return flashcards.first(where: { $0.id == parentId })?.front
    }

    var isSearchActive: Bool {
        !searchText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    init() {
        practiceSentenceStyle = PracticeSentenceStyle.load()
        lastStudySession = StudySessionStore.load()
        loadFlashcards()
        // Drop persisted session if every card was deleted while the app was closed.
        if let session = lastStudySession, session.kind == .vocab,
           resolveLastStudySessionCards().isEmpty {
            lastStudySession = nil
            StudySessionStore.clear()
        }
    }

    func loadFlashcards() {
        flashcards = dbManager.fetchFlashcards()
        let vocab = flashcards.filter { $0.kind == .vocab }
        let examples = flashcards.filter { $0.kind == .example }
        vocabDueCount = FSRSManager.shared.dueCards(from: vocab).count
        exampleDueCount = FSRSManager.shared.dueCards(from: examples).count
        dueCount = vocabDueCount
        pruneSelectedVocabSeedIds(validVocabIds: Set(vocab.map(\.id)))
        pruneLastStudySessionIfNeeded(validVocabIds: Set(vocab.map(\.id)))
    }

    // MARK: - Vocab multi-select (manual practice seeds)

    func beginVocabPracticeSelection() {
        guard selectedDeckKind == .vocab else { return }
        isSelectingVocabForPractice = true
    }

    func cancelVocabPracticeSelection() {
        isSelectingVocabForPractice = false
        selectedVocabSeedIds = []
    }

    func isVocabSeedSelected(_ id: String) -> Bool {
        selectedVocabSeedIds.contains(id)
    }

    /// Toggles selection. Returns `false` when the user tried to add past the seed cap.
    @discardableResult
    func toggleVocabSeedSelection(id: String) -> Bool {
        if let index = selectedVocabSeedIds.firstIndex(of: id) {
            selectedVocabSeedIds.remove(at: index)
            return true
        }
        guard selectedVocabSeedIds.count < PracticeGenerationConfig.maxDueSeeds else {
            return false
        }
        // Only allow vocabulary cards that still exist.
        guard flashcards.contains(where: { $0.id == id && $0.kind == .vocab }) else {
            return false
        }
        selectedVocabSeedIds.append(id)
        return true
    }

    /// Selects visible vocab cards up to the seed cap, preserving list order then existing order.
    func selectVisibleVocabSeeds(from cards: [Flashcard]) {
        let existing = Set(selectedVocabSeedIds)
        var next = selectedVocabSeedIds
        for card in cards where card.kind == .vocab {
            guard next.count < PracticeGenerationConfig.maxDueSeeds else { break }
            if !existing.contains(card.id) {
                next.append(card.id)
            }
        }
        selectedVocabSeedIds = next
    }

    func deselectAllVocabSeeds() {
        selectedVocabSeedIds = []
    }

    /// Starts practice from the current manual selection, then exits selection mode on success path.
    func beginPracticeFromSelectedVocab(
        appLanguage: AppLanguage,
        llmEndpoint: String,
        llmModel: String
    ) {
        let ids = selectedVocabSeedIds
        guard !ids.isEmpty else {
            practiceError = L10n.practiceNoSeeds(appLanguage)
            return
        }
        beginPracticeGeneration(
            appLanguage: appLanguage,
            llmEndpoint: llmEndpoint,
            llmModel: llmModel,
            seedSource: .selectedVocab(ids: ids)
        )
        // Leave multi-select after kicking off generation (selection is retained in seed source).
        isSelectingVocabForPractice = false
        selectedVocabSeedIds = []
    }

    private func pruneSelectedVocabSeedIds(validVocabIds: Set<String>) {
        let pruned = selectedVocabSeedIds.filter { validVocabIds.contains($0) }
        if pruned.count != selectedVocabSeedIds.count {
            selectedVocabSeedIds = pruned
        }
    }

    func dueLabel(for card: Flashcard, language: AppLanguage) -> String {
        let now = Date()
        if card.fsrsCard.due <= now {
            return L10n.dueToday(language)
        }
        let days = max(1, Calendar.current.dateComponents([.day], from: now, to: card.fsrsCard.due).day ?? 1)
        return L10n.dueInDays(language, days: days)
    }

    func isDue(_ card: Flashcard, now: Date = Date()) -> Bool {
        card.fsrsCard.due <= now
    }

    // MARK: - Create / Edit

    func prepareDraft(
        front: String,
        message: Message,
        translatedText: String
    ) {
        let trimmedFront = front.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedFront.isEmpty else { return }

        let suggestedBack = FlashcardTranslator.suggestedBack(
            for: trimmedFront,
            fullMessageContent: message.content,
            existingTranslation: translatedText
        )
        let suggestedPhonics = FlashcardTranslator.autoFillPhonics(for: trimmedFront)

        editingFlashcardId = nil
        draft = FlashcardDraft(
            front: trimmedFront,
            back: suggestedBack,
            phonics: suggestedPhonics,
            autoGeneratedPhonics: suggestedPhonics.isEmpty ? nil : suggestedPhonics,
            sourceMessageId: message.id,
            sourceConversationId: message.conversationId
        )
        duplicateWarning = dbManager.flashcardExists(front: trimmedFront)
        saveError = nil
        isTranslatingDraft = suggestedBack.isEmpty
        isShowingCreateSheet = true
    }

    func prepareEdit(flashcard: Flashcard) {
        editingFlashcardId = flashcard.id
        let phonics = flashcard.phonics ?? ""
        let trackedAutoPhonics = FlashcardTranslator.phonicsMatchAutoGenerated(phonics, for: flashcard.front)
            ? FlashcardTranslator.autoFillPhonics(for: flashcard.front)
            : nil
        draft = FlashcardDraft(
            front: flashcard.front,
            back: flashcard.back,
            phonics: phonics,
            autoGeneratedPhonics: trackedAutoPhonics?.isEmpty == false ? trackedAutoPhonics : nil,
            sourceMessageId: flashcard.sourceMessageId,
            sourceConversationId: flashcard.sourceConversationId
        )
        duplicateWarning = false
        saveError = nil
        isTranslatingDraft = false
        isShowingCreateSheet = true
    }

    func updateDraftFront(_ value: String) {
        guard var currentDraft = draft else { return }
        currentDraft.front = value

        let trimmedFront = value.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmedFront.isEmpty {
            currentDraft.autoGeneratedPhonics = nil
        } else if shouldRefreshAutoPhonics(in: currentDraft) {
            let newPhonics = FlashcardTranslator.autoFillPhonics(for: trimmedFront)
            currentDraft.phonics = newPhonics
            currentDraft.autoGeneratedPhonics = newPhonics.isEmpty ? nil : newPhonics
        }

        draft = currentDraft

        if !trimmedFront.isEmpty {
            duplicateWarning = dbManager.flashcardExists(front: trimmedFront, excludingId: editingFlashcardId)
        } else {
            duplicateWarning = false
        }
    }

    func updateDraftBack(_ value: String) {
        draft?.back = value
        if !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            isTranslatingDraft = false
        }
    }

    func updateDraftPhonics(_ value: String) {
        guard var currentDraft = draft else { return }
        currentDraft.phonics = value
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed != currentDraft.autoGeneratedPhonics?.trimmingCharacters(in: .whitespacesAndNewlines) {
            currentDraft.autoGeneratedPhonics = nil
        }
        draft = currentDraft
    }

    func applyTranslatedBack(_ translation: String) {
        guard var currentDraft = draft else { return }
        let trimmed = translation.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, currentDraft.back.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            isTranslatingDraft = false
            return
        }
        currentDraft.back = trimmed
        draft = currentDraft
        isTranslatingDraft = false
    }

    func cancelDraft() {
        draft = nil
        editingFlashcardId = nil
        duplicateWarning = false
        saveError = nil
        isTranslatingDraft = false
        isShowingCreateSheet = false
    }

    @discardableResult
    func saveDraft(appLanguage: AppLanguage) -> Bool {
        guard let currentDraft = draft else { return false }

        let front = currentDraft.front.trimmingCharacters(in: .whitespacesAndNewlines)
        let back = currentDraft.back.trimmingCharacters(in: .whitespacesAndNewlines)
        var phonics = currentDraft.phonics.trimmingCharacters(in: .whitespacesAndNewlines)
        if phonics.isEmpty {
            phonics = FlashcardTranslator.autoFillPhonics(for: front)
        }

        guard !front.isEmpty else {
            saveError = L10n.flashcardFrontRequired(appLanguage)
            return false
        }
        guard !back.isEmpty else {
            saveError = L10n.flashcardBackRequired(appLanguage)
            return false
        }

        if dbManager.flashcardExists(front: front, excludingId: editingFlashcardId) {
            duplicateWarning = true
            saveError = L10n.flashcardDuplicate(appLanguage)
            return false
        }

        if let editingFlashcardId {
            dbManager.updateFlashcardContent(
                id: editingFlashcardId,
                front: front,
                back: back,
                phonics: phonics.isEmpty ? nil : phonics
            )
            loadFlashcards()
            onLog?("Flashcard updated: \"\(front)\"")
            cancelDraft()
            return true
        }

        let flashcard = Flashcard(
            front: front,
            back: back,
            phonics: phonics.isEmpty ? nil : phonics,
            sourceMessageId: currentDraft.sourceMessageId,
            sourceConversationId: currentDraft.sourceConversationId
        )

        guard dbManager.insertFlashcard(flashcard) != nil else {
            saveError = L10n.flashcardSaveFailed(appLanguage)
            return false
        }

        loadFlashcards()
        onLog?("Flashcard created: \"\(front)\"")
        cancelDraft()
        return true
    }

    func deleteFlashcard(_ flashcard: Flashcard) {
        dbManager.deleteFlashcard(id: flashcard.id)
        loadFlashcards()
        onLog?("Flashcard deleted: \"\(flashcard.front)\"")
    }

    // MARK: - Review Session

    /// Starts an FSRS review for the given kind (defaults to the active dashboard tab).
    func startReviewSession(kind: FlashcardKind? = nil) {
        let reviewKind = kind ?? selectedDeckKind
        currentReviewKind = reviewKind
        // Fresh session snapshot; previous last-session seeds (including persisted) are replaced.
        lastStudySession = StudySessionSnapshot(kind: reviewKind)
        StudySessionStore.clear()
        reviewQueue = dbManager.fetchDueFlashcards(kind: reviewKind)
        currentReviewIndex = 0
        isAnswerRevealed = false
        reviewComplete = reviewQueue.isEmpty
        isShowingReviewSession = true
        onLog?("Review started for \(reviewKind.rawValue) (\(reviewQueue.count) due)")
    }

    func revealAnswer() {
        isAnswerRevealed = true
    }

    func gradeCurrentCard(_ grade: Rating) {
        guard let card = currentReviewCard else { return }

        do {
            let result = try FSRSManager.shared.review(card: card.fsrsCard, grade: grade)
            dbManager.updateFlashcardFSRSState(id: card.id, card: result.card)
            onLog?("Flashcard reviewed (\(grade.stringValue)): \"\(card.front)\"")
        } catch {
            onLog?("Flashcard review failed: \(error.localizedDescription)")
            return
        }

        recordGradedCardInStudySession(card, grade: grade)

        currentReviewIndex += 1
        isAnswerRevealed = false

        if currentReviewIndex >= reviewQueue.count {
            reviewComplete = true
            loadFlashcards()
        }
    }

    func endReviewSession() {
        isShowingReviewSession = false
        reviewQueue = []
        currentReviewIndex = 0
        isAnswerRevealed = false
        reviewComplete = false
        // Keep lastStudySession so post-study practice can still seed from graded cards.
        loadFlashcards()
    }

    // MARK: - Practice Pack (session-scoped; no FSRS / no deck inserts)

    /// Generates a practice pack from vocabulary seeds via the LLM and opens the preview sheet.
    /// - Parameter seedSource: Defaults to the deck preference (due if any, else last study session).
    func beginPracticeGeneration(
        appLanguage: AppLanguage,
        llmEndpoint: String,
        llmModel: String,
        seedSource: PracticeSeedSource? = nil
    ) {
        guard !isGeneratingPractice else { return }

        let source = seedSource ?? preferredDeckPracticeSeedSource
        let seedCards = resolvePracticeSeeds(source: source)
        guard !seedCards.isEmpty else {
            practiceError = L10n.practiceNoSeeds(appLanguage)
            onLog?("Practice generation skipped: no seeds for \(source.analyticsName)")
            return
        }

        let endpoint = llmEndpoint.trimmingCharacters(in: .whitespacesAndNewlines)
        let model = llmModel.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !endpoint.isEmpty else {
            practiceError = L10n.practiceMissingLLMEndpoint(appLanguage)
            onLog?("Practice generation skipped: missing LLM endpoint")
            return
        }

        lastPracticeLLMEndpoint = endpoint
        lastPracticeLLMModel = model.isEmpty ? "default" : model
        lastPracticeAppLanguage = appLanguage
        lastPracticeSeedSource = source

        practiceGenerationTask?.cancel()
        cancelAllItemRegenerations()
        isGeneratingPractice = true
        practiceError = nil
        practiceInfoMessage = nil
        // Close any open preview while regenerating so the dashboard spinner is visible.
        isShowingPracticePreview = false
        practicePack = nil
        selectedPracticeCardIds = []
        savedPracticeCardIds = []
        let seeds = seedCards
        let resolvedModel = lastPracticeLLMModel ?? "default"
        let sourceName = source.analyticsName

        let style = practiceSentenceStyle
        // Resolve known scaffold fronts (no seed-id exclusion — multi-seed co-occurrence is legal).
        // Natural style full opt-out still resolves for logging; generator ignores scaffold when .natural.
        let knownFronts = PracticeKnownVocabulary.resolve(
            from: flashcards,
            seedFrontsForScriptHint: seeds.map(\.front)
        )
        // Approx char total matches resolve budget (+1 separator slack between items).
        let knownChars = knownFronts.isEmpty
            ? 0
            : knownFronts.reduce(0) { $0 + $1.count } + (knownFronts.count - 1)
        let sparse = knownFronts.count < PracticeGenerationConfig.minKnownForRichScaffold
        logPracticeGenerationStart(
            source: source,
            seedCards: seedCards,
            endpoint: endpoint,
            knownCount: knownFronts.count,
            knownChars: knownChars,
            sparse: sparse,
            style: style
        )

        practiceGenerationTask = Task { [weak self] in
            guard let self else { return }
            do {
                let pack = try await PracticeCardGenerator.generatePack(
                    from: seeds,
                    knownFronts: knownFronts,
                    style: style,
                    endpoint: endpoint,
                    model: resolvedModel,
                    appLanguage: appLanguage,
                    apiManager: self.apiManager
                )
                guard !Task.isCancelled else { return }

                self.practicePack = pack
                self.selectedPracticeCardIds = []
                self.savedPracticeCardIds = []
                self.regeneratingPracticeCardIds = []
                self.isGeneratingPractice = false
                self.isShowingPracticePreview = true
                self.onLog?(
                    "Practice pack ready: \(pack.cards.count) card(s) from \(pack.sourceDueCount) seed(s) (\(sourceName))"
                )
            } catch is CancellationError {
                self.isGeneratingPractice = false
                self.onLog?("Practice generation cancelled")
            } catch {
                if Task.isCancelled || Self.isCancellation(error) {
                    self.isGeneratingPractice = false
                    self.onLog?("Practice generation cancelled")
                    return
                }
                self.isGeneratingPractice = false
                self.practicePack = nil
                self.practiceError = L10n.practiceGenerationFailedDetail(
                    appLanguage,
                    detail: error.localizedDescription
                )
                self.onLog?("Practice generation failed: \(error.localizedDescription)")
            }
        }
    }

    /// Regenerates the pack using the last LLM settings and seed source.
    func regeneratePracticePack() {
        guard let endpoint = lastPracticeLLMEndpoint else {
            practiceError = L10n.practiceMissingLLMEndpoint(lastPracticeAppLanguage)
            return
        }
        beginPracticeGeneration(
            appLanguage: lastPracticeAppLanguage,
            llmEndpoint: endpoint,
            llmModel: lastPracticeLLMModel ?? "default",
            seedSource: lastPracticeSeedSource
        )
    }

    /// Resolves vocabulary seeds for practice generation (examples never seed practice).
    /// Results are capped at `PracticeGenerationConfig.maxDueSeeds`.
    func resolvePracticeSeeds(source: PracticeSeedSource) -> [Flashcard] {
        let maxSeeds = PracticeGenerationConfig.maxDueSeeds
        switch source {
        case .dueVocab:
            let due = FSRSManager.shared.dueCards(
                from: flashcards.filter { $0.kind == .vocab }
            )
            return Array(due.prefix(maxSeeds))
        case .lastStudySession:
            return resolveLastStudySessionCards(cappedTo: maxSeeds)
        case .selectedVocab(let ids):
            return Array(resolveSelectedVocabCards(ids: ids).prefix(maxSeeds))
        }
    }

    func removePracticeCard(id: String) {
        cancelItemRegeneration(id: id)
        guard var pack = practicePack else { return }
        pack.cards.removeAll { $0.id == id }
        practicePack = pack
        selectedPracticeCardIds.remove(id)
        savedPracticeCardIds.remove(id)
        regeneratingPracticeCardIds.remove(id)
    }

    func updatePracticeCard(id: String, front: String? = nil, back: String? = nil, phonics: String? = nil) {
        guard var pack = practicePack,
              let index = pack.cards.firstIndex(where: { $0.id == id }) else { return }
        if let front {
            pack.cards[index].front = front
        }
        if let back {
            pack.cards[index].back = back
        }
        if let phonics {
            let trimmed = phonics.trimmingCharacters(in: .whitespacesAndNewlines)
            pack.cards[index].phonics = trimmed.isEmpty ? nil : trimmed
        }
        if front != nil || back != nil || phonics != nil {
            savedPracticeCardIds.remove(id)
        }
        practicePack = pack
    }

    func togglePracticeCardSelection(id: String) {
        if selectedPracticeCardIds.contains(id) {
            selectedPracticeCardIds.remove(id)
        } else {
            selectedPracticeCardIds.insert(id)
        }
    }

    func selectAllPracticeCards() {
        let ids = (practicePack?.cards ?? practiceQueue).map(\.id)
        selectedPracticeCardIds = Set(ids)
    }

    func deselectAllPracticeCards() {
        selectedPracticeCardIds = []
    }

    func isPracticeCardSelected(_ id: String) -> Bool {
        selectedPracticeCardIds.contains(id)
    }

    func isPracticeCardSaved(_ id: String) -> Bool {
        savedPracticeCardIds.contains(id)
    }

    func isRegeneratingPracticeCard(_ id: String) -> Bool {
        regeneratingPracticeCardIds.contains(id)
    }

    /// Regenerates one practice example in-place (keeps card id for stable selection/UI).
    func regeneratePracticeCard(id: String) {
        guard !isGeneratingPractice else { return }
        guard !regeneratingPracticeCardIds.contains(id) else { return }
        guard let endpoint = lastPracticeLLMEndpoint else {
            practiceError = L10n.practiceMissingLLMEndpoint(lastPracticeAppLanguage)
            return
        }
        guard let pack = practicePack,
              let index = pack.cards.firstIndex(where: { $0.id == id }) else { return }

        let existing = pack.cards[index]
        guard let seed = resolveSeed(for: existing) else {
            practiceError = L10n.practiceRegenerateMissingParent(lastPracticeAppLanguage)
            onLog?("Practice single regenerate failed: missing parent seed for \(id)")
            return
        }

        let model = lastPracticeLLMModel ?? "default"
        let appLanguage = lastPracticeAppLanguage
        let avoid = pack.cards.map(\.front)

        let style = practiceSentenceStyle
        // Fresh known set at regenerate time; do not exclude seed id.
        let knownFronts = PracticeKnownVocabulary.resolve(
            from: flashcards,
            seedFrontsForScriptHint: [seed.front]
        )
        let knownChars = knownFronts.isEmpty
            ? 0
            : knownFronts.reduce(0) { $0 + $1.count } + (knownFronts.count - 1)

        cancelItemRegeneration(id: id)
        regeneratingPracticeCardIds.insert(id)
        practiceError = nil
        if style == .natural {
            onLog?(
                "Practice single regenerate started for parent \"\(seed.front)\", style=natural, scaffold=off"
            )
        } else {
            onLog?(
                "Practice single regenerate started for parent \"\(seed.front)\", known=\(knownFronts.count) knownChars=\(knownChars) style=\(style.rawValue)"
            )
        }

        let task = Task { [weak self] in
            guard let self else { return }
            defer {
                self.regeneratingPracticeCardIds.remove(id)
                self.itemRegenerationTasks[id] = nil
            }
            do {
                let generated = try await PracticeCardGenerator.regenerateExample(
                    seed: seed,
                    existingSentences: avoid,
                    knownFronts: knownFronts,
                    style: style,
                    endpoint: endpoint,
                    model: model,
                    appLanguage: appLanguage,
                    apiManager: self.apiManager
                )
                guard !Task.isCancelled else { return }
                guard var currentPack = self.practicePack,
                      let currentIndex = currentPack.cards.firstIndex(where: { $0.id == id }) else { return }

                currentPack.cards[currentIndex] = PracticeCard(
                    id: id,
                    front: generated.front,
                    back: generated.back,
                    phonics: generated.phonics,
                    parentFlashcardId: generated.parentFlashcardId ?? seed.id,
                    parentFront: generated.parentFront ?? seed.front
                )
                self.practicePack = currentPack
                self.savedPracticeCardIds.remove(id)
                self.onLog?("Practice single regenerate ready: \"\(generated.front)\"")
            } catch is CancellationError {
                self.onLog?("Practice single regenerate cancelled")
            } catch {
                if Task.isCancelled || Self.isCancellation(error) {
                    self.onLog?("Practice single regenerate cancelled")
                    return
                }
                self.practiceError = L10n.practiceGenerationFailedDetail(
                    appLanguage,
                    detail: error.localizedDescription
                )
                self.onLog?("Practice single regenerate failed: \(error.localizedDescription)")
            }
        }
        itemRegenerationTasks[id] = task
    }

    /// Pins selected practice cards into the main deck as normal flashcards (new FSRS state).
    @discardableResult
    func saveSelectedPracticeCardsToDeck(appLanguage: AppLanguage) -> PracticeSaveResult {
        let cards = selectedPracticeCards
        let result = savePracticeCardsToDeck(cards, appLanguage: appLanguage)
        practiceInfoMessage = L10n.practiceSaveResultSummary(
            appLanguage,
            saved: result.savedCount,
            duplicates: result.duplicateCount,
            failed: result.failedCount
        )
        return result
    }

    /// Pins a single practice card into the main deck.
    @discardableResult
    func savePracticeCardToDeck(id: String, appLanguage: AppLanguage) -> PracticeSaveResult {
        let source = practicePack?.cards ?? practiceQueue
        guard let card = source.first(where: { $0.id == id }) else {
            return PracticeSaveResult()
        }
        let result = savePracticeCardsToDeck([card], appLanguage: appLanguage)
        practiceInfoMessage = L10n.practiceSaveResultSummary(
            appLanguage,
            saved: result.savedCount,
            duplicates: result.duplicateCount,
            failed: result.failedCount
        )
        return result
    }

    /// Closes the preview sheet; the session sheet is presented from preview `onDismiss`.
    func startPracticeSession() {
        guard let pack = practicePack else { return }
        let validCards = pack.cards.filter {
            !$0.front.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                && !$0.back.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
        guard !validCards.isEmpty else { return }
        practiceQueue = validCards
        let queueIds = Set(validCards.map(\.id))
        selectedPracticeCardIds = selectedPracticeCardIds.intersection(queueIds)
        currentPracticeIndex = 0
        isPracticeAnswerRevealed = false
        practiceComplete = false
        pendingPracticeSessionStart = true
        isShowingPracticePreview = false
        onLog?("Practice session starting (\(practiceQueue.count) cards)")
    }

    /// Called after the preview sheet fully dismisses when the user chose Start Practice.
    func presentPendingPracticeSessionIfNeeded() {
        guard pendingPracticeSessionStart else { return }
        pendingPracticeSessionStart = false
        guard !practiceQueue.isEmpty else {
            discardPracticePack()
            return
        }
        isShowingPracticeSession = true
        onLog?("Practice session presented (\(practiceQueue.count) cards)")
    }

    func revealPracticeAnswer() {
        isPracticeAnswerRevealed = true
    }

    /// Advances past the current practice card without touching FSRS or the main deck.
    func advancePracticeCard() {
        guard currentPracticeCard != nil else { return }
        currentPracticeIndex += 1
        isPracticeAnswerRevealed = false
        if currentPracticeIndex >= practiceQueue.count {
            practiceComplete = true
            onLog?("Practice session complete")
        }
    }

    func discardPracticePack() {
        let hadPack = practicePack != nil
            || isShowingPracticeSession
            || isShowingPracticePreview
            || pendingPracticeSessionStart
            || isGeneratingPractice
            || !itemRegenerationTasks.isEmpty
        practiceGenerationTask?.cancel()
        practiceGenerationTask = nil
        cancelAllItemRegenerations()
        practicePack = nil
        practiceError = nil
        practiceInfoMessage = nil
        isGeneratingPractice = false
        isShowingPracticePreview = false
        isShowingPracticeSession = false
        pendingPracticeSessionStart = false
        practiceQueue = []
        currentPracticeIndex = 0
        isPracticeAnswerRevealed = false
        practiceComplete = false
        selectedPracticeCardIds = []
        savedPracticeCardIds = []
        regeneratingPracticeCardIds = []
        if hadPack {
            onLog?("Practice pack discarded")
        }
    }

    private func savePracticeCardsToDeck(
        _ cards: [PracticeCard],
        appLanguage: AppLanguage
    ) -> PracticeSaveResult {
        var result = PracticeSaveResult()

        for card in cards {
            let front = card.front.trimmingCharacters(in: .whitespacesAndNewlines)
            let back = card.back.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !front.isEmpty, !back.isEmpty else {
                result.skippedEmptyCount += 1
                continue
            }

            if dbManager.flashcardExists(front: front) {
                result.duplicateCount += 1
                savedPracticeCardIds.insert(card.id)
                onLog?("Practice save skipped (duplicate): \"\(front)\"")
                continue
            }

            var phonics = card.phonics?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            if phonics.isEmpty {
                phonics = FlashcardTranslator.autoFillPhonics(for: front)
            }

            let flashcard = Flashcard(
                front: front,
                back: back,
                phonics: phonics.isEmpty ? nil : phonics,
                kind: .example,
                parentFlashcardId: card.parentFlashcardId
            )

            if dbManager.insertFlashcard(flashcard) != nil {
                result.savedCount += 1
                savedPracticeCardIds.insert(card.id)
                onLog?("Practice example saved to gym: \"\(front)\"")
            } else {
                result.failedCount += 1
                onLog?("Practice save failed: \"\(front)\"")
            }
        }

        if result.savedCount > 0 {
            loadFlashcards()
            // Land the user on the gym tab so the save is visible.
            selectedDeckKind = .example
        }

        // Clear selection for successfully handled cards (saved or already-duplicate).
        if result.savedCount > 0 || result.duplicateCount > 0 {
            let handledFronts = Set(
                cards
                    .map { $0.front.trimmingCharacters(in: .whitespacesAndNewlines) }
                    .filter { !$0.isEmpty }
            )
            let source = practicePack?.cards ?? practiceQueue
            for card in source where handledFronts.contains(card.front.trimmingCharacters(in: .whitespacesAndNewlines)) {
                if savedPracticeCardIds.contains(card.id) {
                    selectedPracticeCardIds.remove(card.id)
                }
            }
        }

        _ = appLanguage // reserved for localized logging if needed later
        return result
    }

    private func recordGradedCardInStudySession(_ card: Flashcard, grade: Rating) {
        let entry = StudySessionGradedEntry(id: card.id, grade: grade)
        if var session = lastStudySession {
            if let index = session.gradedEntries.firstIndex(where: { $0.id == card.id }) {
                session.gradedEntries[index] = entry
            } else {
                session.gradedEntries.append(entry)
            }
            session.completedAt = Date()
            lastStudySession = session
        } else {
            lastStudySession = StudySessionSnapshot(
                kind: currentReviewKind,
                gradedEntries: [entry],
                completedAt: Date()
            )
        }
        // Only vocab sessions seed practice; still persist kind so Examples sessions don't revive later.
        if lastStudySession?.kind == .vocab {
            StudySessionStore.save(lastStudySession)
        } else {
            StudySessionStore.clear()
        }
    }

    /// Vocab cards from the last study session.
    /// Prefer Again/Hard (weak) first when capping; preserve relative study order within each tier.
    private func resolveLastStudySessionCards(
        cappedTo maxSeeds: Int = PracticeGenerationConfig.maxDueSeeds
    ) -> [Flashcard] {
        guard let session = lastStudySession, session.kind == .vocab else { return [] }
        let byId = Dictionary(uniqueKeysWithValues: flashcards.map { ($0.id, $0) })

        var weak: [Flashcard] = []
        var strong: [Flashcard] = []
        for entry in session.gradedEntries {
            guard let card = byId[entry.id], card.kind == .vocab else { continue }
            if entry.isWeak {
                weak.append(card)
            } else {
                strong.append(card)
            }
        }
        return Array((weak + strong).prefix(maxSeeds))
    }

    private func pruneLastStudySessionIfNeeded(validVocabIds: Set<String>) {
        guard var session = lastStudySession, session.kind == .vocab else { return }
        let before = session.gradedEntries.count
        session.gradedEntries.removeAll { !validVocabIds.contains($0.id) }
        guard session.gradedEntries.count != before else { return }
        if session.gradedEntries.isEmpty {
            lastStudySession = nil
            StudySessionStore.clear()
        } else {
            lastStudySession = session
            StudySessionStore.save(session)
        }
    }

    private func logPracticeGenerationStart(
        source: PracticeSeedSource,
        seedCards: [Flashcard],
        endpoint: String,
        knownCount: Int,
        knownChars: Int,
        sparse: Bool,
        style: PracticeSentenceStyle
    ) {
        // Natural full opt-out: omit scaffold metrics so logs match generator behavior.
        var detail: String
        if style == .natural {
            detail = "Practice generation from \(source.analyticsName) (\(seedCards.count) seeds), style=natural, scaffold=off"
        } else {
            detail = "Practice generation from \(source.analyticsName) (\(seedCards.count) seeds), \(knownCount) known-scaffold words, knownChars=\(knownChars), style=\(style.rawValue), sparse=\(sparse)"
        }
        if source == .lastStudySession, let session = lastStudySession {
            let weakIds = Set(session.gradedEntries.filter(\.isWeak).map(\.id))
            let weakInSeeds = seedCards.filter { weakIds.contains($0.id) }.count
            if weakInSeeds > 0 {
                detail += ", \(weakInSeeds) weak-first"
            }
        }
        onLog?(detail)
        onLog?("Practice generation endpoint: \(endpoint)")
    }

    /// Manual selection resolved in selection order; drops missing / non-vocab ids.
    private func resolveSelectedVocabCards(ids: [String]? = nil) -> [Flashcard] {
        let orderedIds = ids ?? selectedVocabSeedIds
        let byId = Dictionary(uniqueKeysWithValues: flashcards.map { ($0.id, $0) })
        return orderedIds.compactMap { id -> Flashcard? in
            guard let card = byId[id], card.kind == .vocab else { return nil }
            return card
        }
    }

    private func resolveSeed(for practiceCard: PracticeCard) -> Flashcard? {
        if let parentId = practiceCard.parentFlashcardId,
           let match = flashcards.first(where: { $0.id == parentId }) {
            return match
        }
        if let parentFront = practiceCard.parentFront {
            let key = parentFront.trimmingCharacters(in: .whitespacesAndNewlines)
            if let match = flashcards.first(where: {
                $0.front.trimmingCharacters(in: .whitespacesAndNewlines) == key
            }) {
                return match
            }
        }
        return nil
    }

    private func cancelItemRegeneration(id: String) {
        itemRegenerationTasks[id]?.cancel()
        itemRegenerationTasks[id] = nil
        regeneratingPracticeCardIds.remove(id)
    }

    private func cancelAllItemRegenerations() {
        for (_, task) in itemRegenerationTasks {
            task.cancel()
        }
        itemRegenerationTasks.removeAll()
        regeneratingPracticeCardIds = []
    }

    private func shouldRefreshAutoPhonics(in draft: FlashcardDraft) -> Bool {
        let trimmedPhonics = draft.phonics.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmedPhonics.isEmpty { return true }
        guard let autoGeneratedPhonics = draft.autoGeneratedPhonics else { return false }
        return trimmedPhonics == autoGeneratedPhonics.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func isCancellation(_ error: Error) -> Bool {
        if error is CancellationError { return true }
        let nsError = error as NSError
        return nsError.domain == NSURLErrorDomain && nsError.code == NSURLErrorCancelled
    }
}