import Foundation
import SwiftUI
import Combine
import FSRS

struct FlashcardDraft: Equatable {
    var front: String
    var back: String
    var phonics: String
    /// Tracks the last auto-filled pinyin so manual phonics edits are not overwritten.
    var autoGeneratedPhonics: String?
    var sourceMessageId: String?
    var sourceConversationId: String?
}

enum AppSection: String, CaseIterable, Identifiable {
    case conversations
    case flashcards

    var id: String { rawValue }
}

@MainActor
final class FlashcardViewModel: ObservableObject {
    private let dbManager = DatabaseManager()

    @Published var flashcards: [Flashcard] = []
    @Published var dueCount: Int = 0
    @Published var searchText: String = ""
    @Published var draft: FlashcardDraft?
    @Published var editingFlashcardId: String?
    @Published var isShowingCreateSheet = false
    @Published var isTranslatingDraft = false
    @Published var duplicateWarning = false
    @Published var saveError: String?

    @Published var isShowingReviewSession = false
    @Published var reviewQueue: [Flashcard] = []
    @Published var currentReviewIndex = 0
    @Published var isAnswerRevealed = false
    @Published var reviewComplete = false

    var onLog: ((String) -> Void)?

    var currentReviewCard: Flashcard? {
        guard currentReviewIndex < reviewQueue.count else { return nil }
        return reviewQueue[currentReviewIndex]
    }

    var isEditing: Bool { editingFlashcardId != nil }

    var filteredFlashcards: [Flashcard] {
        let query = searchText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !query.isEmpty else { return flashcards }

        return flashcards.filter { card in
            card.front.localizedCaseInsensitiveContains(query)
                || card.back.localizedCaseInsensitiveContains(query)
                || (card.phonics?.localizedCaseInsensitiveContains(query) ?? false)
        }
    }

    var isSearchActive: Bool {
        !searchText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    init() {
        loadFlashcards()
    }

    func loadFlashcards() {
        flashcards = dbManager.fetchFlashcards()
        dueCount = FSRSManager.shared.dueCards(from: flashcards).count
    }

    func dueLabel(for card: Flashcard, language: AppLanguage) -> String {
        let now = Date()
        if card.fsrsCard.due <= now {
            return L10n.dueToday(language)
        }
        let days = max(1, Calendar.current.dateComponents([.day], from: now, to: card.fsrsCard.due).day ?? 1)
        return L10n.dueInDays(language, days: days)
    }

    func isDue(_ card: Flashcard, now: Date = Date()) -> Bool {
        card.fsrsCard.due <= now
    }

    // MARK: - Create / Edit

    func prepareDraft(
        front: String,
        message: Message,
        translatedText: String
    ) {
        let trimmedFront = front.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedFront.isEmpty else { return }

        let suggestedBack = FlashcardTranslator.suggestedBack(
            for: trimmedFront,
            fullMessageContent: message.content,
            existingTranslation: translatedText
        )
        let suggestedPhonics = FlashcardTranslator.autoFillPhonics(for: trimmedFront)

        editingFlashcardId = nil
        draft = FlashcardDraft(
            front: trimmedFront,
            back: suggestedBack,
            phonics: suggestedPhonics,
            autoGeneratedPhonics: suggestedPhonics.isEmpty ? nil : suggestedPhonics,
            sourceMessageId: message.id,
            sourceConversationId: message.conversationId
        )
        duplicateWarning = dbManager.flashcardExists(front: trimmedFront)
        saveError = nil
        isTranslatingDraft = suggestedBack.isEmpty
        isShowingCreateSheet = true
    }

    func prepareEdit(flashcard: Flashcard) {
        editingFlashcardId = flashcard.id
        let phonics = flashcard.phonics ?? ""
        let trackedAutoPhonics = FlashcardTranslator.phonicsMatchAutoGenerated(phonics, for: flashcard.front)
            ? FlashcardTranslator.autoFillPhonics(for: flashcard.front)
            : nil
        draft = FlashcardDraft(
            front: flashcard.front,
            back: flashcard.back,
            phonics: phonics,
            autoGeneratedPhonics: trackedAutoPhonics?.isEmpty == false ? trackedAutoPhonics : nil,
            sourceMessageId: flashcard.sourceMessageId,
            sourceConversationId: flashcard.sourceConversationId
        )
        duplicateWarning = false
        saveError = nil
        isTranslatingDraft = false
        isShowingCreateSheet = true
    }

    func updateDraftFront(_ value: String) {
        guard var currentDraft = draft else { return }
        currentDraft.front = value

        let trimmedFront = value.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmedFront.isEmpty {
            currentDraft.autoGeneratedPhonics = nil
        } else if shouldRefreshAutoPhonics(in: currentDraft) {
            let newPhonics = FlashcardTranslator.autoFillPhonics(for: trimmedFront)
            currentDraft.phonics = newPhonics
            currentDraft.autoGeneratedPhonics = newPhonics.isEmpty ? nil : newPhonics
        }

        draft = currentDraft

        if !trimmedFront.isEmpty {
            duplicateWarning = dbManager.flashcardExists(front: trimmedFront, excludingId: editingFlashcardId)
        } else {
            duplicateWarning = false
        }
    }

    func updateDraftBack(_ value: String) {
        draft?.back = value
        if !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            isTranslatingDraft = false
        }
    }

    func updateDraftPhonics(_ value: String) {
        guard var currentDraft = draft else { return }
        currentDraft.phonics = value
        let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmed != currentDraft.autoGeneratedPhonics?.trimmingCharacters(in: .whitespacesAndNewlines) {
            currentDraft.autoGeneratedPhonics = nil
        }
        draft = currentDraft
    }

    func applyTranslatedBack(_ translation: String) {
        guard var currentDraft = draft else { return }
        let trimmed = translation.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, currentDraft.back.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            isTranslatingDraft = false
            return
        }
        currentDraft.back = trimmed
        draft = currentDraft
        isTranslatingDraft = false
    }

    func cancelDraft() {
        draft = nil
        editingFlashcardId = nil
        duplicateWarning = false
        saveError = nil
        isTranslatingDraft = false
        isShowingCreateSheet = false
    }

    @discardableResult
    func saveDraft(appLanguage: AppLanguage) -> Bool {
        guard let currentDraft = draft else { return false }

        let front = currentDraft.front.trimmingCharacters(in: .whitespacesAndNewlines)
        let back = currentDraft.back.trimmingCharacters(in: .whitespacesAndNewlines)
        var phonics = currentDraft.phonics.trimmingCharacters(in: .whitespacesAndNewlines)
        if phonics.isEmpty {
            phonics = FlashcardTranslator.autoFillPhonics(for: front)
        }

        guard !front.isEmpty else {
            saveError = L10n.flashcardFrontRequired(appLanguage)
            return false
        }
        guard !back.isEmpty else {
            saveError = L10n.flashcardBackRequired(appLanguage)
            return false
        }

        if dbManager.flashcardExists(front: front, excludingId: editingFlashcardId) {
            duplicateWarning = true
            saveError = L10n.flashcardDuplicate(appLanguage)
            return false
        }

        if let editingFlashcardId {
            dbManager.updateFlashcardContent(
                id: editingFlashcardId,
                front: front,
                back: back,
                phonics: phonics.isEmpty ? nil : phonics
            )
            loadFlashcards()
            onLog?("Flashcard updated: \"\(front)\"")
            cancelDraft()
            return true
        }

        let flashcard = Flashcard(
            front: front,
            back: back,
            phonics: phonics.isEmpty ? nil : phonics,
            sourceMessageId: currentDraft.sourceMessageId,
            sourceConversationId: currentDraft.sourceConversationId
        )

        guard dbManager.insertFlashcard(flashcard) != nil else {
            saveError = L10n.flashcardSaveFailed(appLanguage)
            return false
        }

        loadFlashcards()
        onLog?("Flashcard created: \"\(front)\"")
        cancelDraft()
        return true
    }

    func deleteFlashcard(_ flashcard: Flashcard) {
        dbManager.deleteFlashcard(id: flashcard.id)
        loadFlashcards()
        onLog?("Flashcard deleted: \"\(flashcard.front)\"")
    }

    // MARK: - Review Session

    func startReviewSession() {
        reviewQueue = dbManager.fetchDueFlashcards()
        currentReviewIndex = 0
        isAnswerRevealed = false
        reviewComplete = reviewQueue.isEmpty
        isShowingReviewSession = true
    }

    func revealAnswer() {
        isAnswerRevealed = true
    }

    func gradeCurrentCard(_ grade: Rating) {
        guard let card = currentReviewCard else { return }

        do {
            let result = try FSRSManager.shared.review(card: card.fsrsCard, grade: grade)
            dbManager.updateFlashcardFSRSState(id: card.id, card: result.card)
            onLog?("Flashcard reviewed (\(grade.stringValue)): \"\(card.front)\"")
        } catch {
            onLog?("Flashcard review failed: \(error.localizedDescription)")
            return
        }

        currentReviewIndex += 1
        isAnswerRevealed = false

        if currentReviewIndex >= reviewQueue.count {
            reviewComplete = true
            loadFlashcards()
        }
    }

    func endReviewSession() {
        isShowingReviewSession = false
        reviewQueue = []
        currentReviewIndex = 0
        isAnswerRevealed = false
        reviewComplete = false
        loadFlashcards()
    }

    private func shouldRefreshAutoPhonics(in draft: FlashcardDraft) -> Bool {
        let trimmedPhonics = draft.phonics.trimmingCharacters(in: .whitespacesAndNewlines)
        if trimmedPhonics.isEmpty { return true }
        guard let autoGeneratedPhonics = draft.autoGeneratedPhonics else { return false }
        return trimmedPhonics == autoGeneratedPhonics.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}